import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Sidebar from "@/components/sidebar/sidebar";

import Script from 'next/script'; // Vergeet niet Script te importeren


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <head>
        {/* Laad Font Awesome-script asynchroon */}
        <Script
          src="https://kit.fontawesome.com/8a111eb1bb.js"
          crossOrigin="anonymous"
          strategy="afterInteractive" // Dit zorgt ervoor dat het script pas na de interactie wordt geladen
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <main style={{ flex: 1 }}>
          <Sidebar />

          {children}
        </main>
      </body>
    </html>
  );
}