import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Sidebar from "@/components/sidebar/sidebar";
import Script from "next/script";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script src="https://kit.fontawesome.com/e0075003b5.js"  defer></Script>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Sidebar/>
        <main style={{ flex: 1, padding: "20px" }}>

          {children}
        </main>
    
    </body>
  </html>
  );
}
